import { Preferences } from "./types";

export const defaultPreferences: Preferences = {
  likes: [
    "Kazakhstani food — soups, salads, beshbarmak (absolute favorite), manti",
    "Green mix salad of arugula and baby spinach from Netto — no other salad",
    "Green Granny Smith apples",
    "Kiwis, watermelons",
    "Roasted walnuts, roasted cashews",
    "Fully hard boiled eggs or scrambled eggs only",
    "Spanish omelette — fully cooked through",
    "Goat cheese and aged Havarti",
    "Oat milk — only Oatly brand, full fat yoghurt",
    "Turkish breakfast is the favorite thing — but not so much sucuk",
    "Mercimek corbasi (lentil soup), tavuk corbasi (chicken soup), simple Turkish soups",
    "Raw tomatoes only",
    "Kazakh salads — pickled carrots, crème fraîche with tomatoes/cucumbers/dill, all Central Asian salads",
    "Lamb soup — boiled in water with potatoes and meat",
    "Lamb over beef",
    "Baked or grilled food only",
    "Sushi — sometimes, once a month max",
    "Pizza — chicken or Margherita with chicken/beef, Turkish pide",
    "Carrots and hummus",
    "Nachos and popcorn as snack",
    "Danish Nordic crisps and nut crisps",
    "Parsley and dill — loves them",
    "Sirniki (Russian cheese pancakes)",
    "Liver pâté",
    "Sourdough bread",
    "Bread with parsley-dill pesto sauce mixed with sour cream",
    "Tomatoes with sesame drizzled on top",
    "Basil, poached eggs, crushed pistachio",
    "Luke warm water in morning",
    "Light ginger tea",
    "Nuts in morning",
    "Raw smell of mutton or goat meat",
    "Bland food preferred",
  ],
  dislikes: [
    "All salads except arugula + baby spinach mix",
    "Cantaloupe — absolutely not",
    "Pineapple — cannot eat",
    "Half cooked / runny eggs",
    "Cooked tomatoes — only raw",
    "Boiled carrots",
    "Italian breakfast",
    "Too much oil or visibly oily food",
    "Ginger in food (light ginger tea is fine)",
    "Spices, chillies, onions, garlic",
    "Burnt food, barbeque, burnt texture",
    "Cinnamon, cardamom, or any strong warm spice — subtle or very very less only",
    "Any food with strong smell",
    "Pasta, spaghetti, lasagna of any kind",
    "Biriyani and Indian food — except very mild butter chicken occasionally",
    "Sucuk (not a favorite in Turkish breakfast)",
  ],
  restrictions: [
    "PREGNANT — all meals must be pregnancy-safe",
    "NO pork, NO bacon — absolutely not",
    "NO fried food of any kind — ABSOLUTE rule",
    "No oil cooking — try to use no oil at all",
    "No charcoal grilled food",
    "Only baked or grilled (oven/pan) food",
    "No strong spices or chillies",
    "No raw or undercooked eggs",
    "No raw fish (sushi once a month — cooked rolls only)",
    "No strong-smelling warm spices (cinnamon, cardamom)",
  ],
  notes:
    "She is from Kazakhstan. Comfort food is just boiled mutton with cumin seeds, potatoes, and raw onions. Balanced diet should include: soup, nuts, veggies, fruits, meat/chicken, bread/rice/roti/paratha across the day. Keep meals simple, clean, and bland. Focus on nutrition for pregnancy.",
};
